"""add job_applications table (R4)

Revision ID: 218c4c2840e0
Revises: d8447d8bdc7b
Create Date: 2026-08-16 23:48:34.217830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218c4c2840e0'
down_revision: Union[str, Sequence[str], None] = 'd8447d8bdc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('saved', 'applied', 'interviewing', 'offer', 'rejected', 'withdrawn')", name='ck_job_applications_status'),
    sa.ForeignKeyConstraint(['listing_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_job_applications_user_listing')
    )
    op.create_index(op.f('ix_job_applications_applied_at'), 'job_applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_job_applications_listing_id'), 'job_applications', ['listing_id'], unique=False)
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    op.create_index(op.f('ix_job_applications_user_id'), 'job_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_user_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_listing_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_applied_at'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
