"""add job_listings and h1b_employers

Revision ID: 3c63c77a5807
Revises: ccda0b64e306
Create Date: 2026-06-12 23:55:13.523168

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c63c77a5807'
down_revision: Union[str, Sequence[str], None] = 'ccda0b64e306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h1b_employers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_name_normalized', sa.String(length=512), nullable=False),
    sa.Column('employer_name_display', sa.String(length=512), nullable=False),
    sa.Column('lca_count_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lca_count_last_12mo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('most_recent_filing_year', sa.Integer(), nullable=True),
    sa.Column('most_recent_filing_date', sa.Date(), nullable=True),
    sa.Column('top_job_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_h1b_employers_employer_name_normalized'), 'h1b_employers', ['employer_name_normalized'], unique=True)
    op.create_table('job_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_clean', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='new', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sponsorship_status', sa.String(length=32), nullable=True),
    sa.Column('sponsorship_evidence', sa.Text(), nullable=True),
    sa.Column('sponsorship_confidence', sa.Float(), nullable=True),
    sa.Column('h1b_lca_count_recent', sa.Integer(), nullable=True),
    sa.Column('h1b_lca_year', sa.Integer(), nullable=True),
    sa.Column('cpt_opt_friendly', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sponsorship_status IS NULL OR sponsorship_status IN ('sponsors', 'no_sponsorship', 'us_citizen_only', 'unclear')", name='ck_job_listings_sponsorship_status'),
    sa.CheckConstraint("status IN ('new', 'saved', 'applied', 'rejected', 'interviewing', 'dismissed')", name='ck_job_listings_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_job_listings_source_sourceid')
    )
    op.create_index(op.f('ix_job_listings_company'), 'job_listings', ['company'], unique=False)
    op.create_index(op.f('ix_job_listings_source'), 'job_listings', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_listings_source'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_company'), table_name='job_listings')
    op.drop_table('job_listings')
    op.drop_index(op.f('ix_h1b_employers_employer_name_normalized'), table_name='h1b_employers')
    op.drop_table('h1b_employers')
    # ### end Alembic commands ###
