"""add agent_runs table

Revision ID: d8447d8bdc7b
Revises: e6795c2e1478
Create Date: 2026-06-19 00:19:12.670852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8447d8bdc7b'
down_revision: Union[str, Sequence[str], None] = 'e6795c2e1478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result_summary', sa.Text(), nullable=True),
    sa.Column('classifier_reasoning', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('langsmith_trace_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("module IN ('master_agent', 'resume_customizer', 'email_triage', 'job_board')", name='ck_agent_runs_module'),
    sa.CheckConstraint("status IN ('success', 'clarify', 'error', 'tool_error')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_intent'), 'agent_runs', ['intent'], unique=False)
    op.create_index(op.f('ix_agent_runs_langsmith_trace_id'), 'agent_runs', ['langsmith_trace_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_module'), 'agent_runs', ['module'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_module'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_langsmith_trace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_intent'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
