"""add emails table for M3

Revision ID: e6795c2e1478
Revises: 3c63c77a5807
Create Date: 2026-06-13 14:56:14.728432

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6795c2e1478'
down_revision: Union[str, Sequence[str], None] = '3c63c77a5807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('thread_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('sender_name', sa.String(length=512), nullable=True),
    sa.Column('recipient', sa.String(length=512), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('body_full', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('classifier_reasoning', sa.Text(), nullable=True),
    sa.Column('classifier_version', sa.Integer(), nullable=True),
    sa.Column('linked_job_listing_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IS NULL OR category IN ('interview', 'recruiter', 'rejection', 'offer', 'spam', 'newsletter', 'application_confirmation', 'other')", name='ck_emails_category'),
    sa.CheckConstraint("source IN ('outlook', 'gmail')", name='ck_emails_source'),
    sa.CheckConstraint('importance_score IS NULL OR (importance_score >= 1 AND importance_score <= 5)', name='ck_emails_importance_range'),
    sa.ForeignKeyConstraint(['linked_job_listing_id'], ['job_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'message_id', name='uq_emails_user_source_msg')
    )
    op.create_index(op.f('ix_emails_linked_job_listing_id'), 'emails', ['linked_job_listing_id'], unique=False)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_emails_sender'), 'emails', ['sender'], unique=False)
    op.create_index(op.f('ix_emails_source'), 'emails', ['source'], unique=False)
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_source'), table_name='emails')
    op.drop_index(op.f('ix_emails_sender'), table_name='emails')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_linked_job_listing_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
